# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestBeauceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestBeauceApp

  target 'TestBeauceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestBeauceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
# Required by RNFirebase
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Firestore', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'
